apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-minio
spec:
  storageClassName: nfs-manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: /var/nfs/k8s
    server: 192.168.50.132
    readOnly: false