# Generated by Django 2.1.7 on 2019-02-20 19:05

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('assigned', models.DateTimeField(blank=True, null=True)),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('label', models.CharField(blank=True, default='', max_length=250)),
                ('command', models.TextField()),
                ('job_type', models.TextField()),
                ('parameters', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('priority', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='L', max_length=1)),
                ('status', models.CharField(choices=[('S', 'Submitted'), ('A', 'Assigned'), ('C', 'Completed')], default='S', max_length=1)),
                ('success', models.BooleanField(null=True)),
                ('result_message', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('submitted',),
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('worker_name', models.TextField()),
                ('system_info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('capabilities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=None)),
                ('paused', models.BooleanField()),
                ('schedule', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='worker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_v1.Worker'),
        ),
    ]
