# Generated by Django 2.1.7 on 2019-03-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0003_auto_20190308_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
