# Generated by Django 2.1 on 2020-01-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0005_auto_20190918_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='task_id',
            field=models.UUIDField(default='00000000-0000-0000-0000-000000000000'),
        ),
    ]
