# Generated by Django 2.1 on 2020-02-13 23:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0006_job_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
