# Generated by Django 3.0.4 on 2020-04-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0007_job_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='worker_id',
        ),
        migrations.AddField(
            model_name='job',
            name='aoi_name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
